### ISSUE TITLE
分页时重复加载的问题

### ISSUE THREAD

**Issue by linziguan** [SitePen/dgrid#1034]
var _containerId = '${param._containerId}';
            require([
                "dgrid/OnDemandGrid",
                "dgrid/extensions/Pagination",
                "dojox/data/QueryReadStore",
                "dojo/store/DataStore",
                "dojo/parser",
                "dijit/registry",
                "dojox/widget/DialogSimple",
                "dojo/topic",
                "dojo/_base/declare",
                "dojo/domReady!"
            ], function (Grid, Pagination, JsonStore, DataStore, parser, registry, Dialog, topic, declare) {

                var jsonStore = new JsonStore({url: ctx + "/funcPointAction/queryFuncPoints.do"});
                var store = new DataStore({store: jsonStore});

                var columns = [
                    {label: "功能点名称", field: "name", width: "120px"},
                    {label: "URL地址", field: "url", width: "300px"}
                ];

                var grid = new (declare([Grid,Pagination]))({
                    columns: columns,
                    store:store,
                    firstLastArrows: true,
                    rowsPerPage:30,
                    pageSizeOptions: [30, 50, 100]
                });
                var container = registry.byId(_containerId);
                container.addChild(grid);
            });
会重复ajax两次

当我把Pagination.js里的refresh的this.inherited(arguments);注释之后：
refresh: function(){
			var self = this;
			
			//this.inherited(arguments);
			
			if(!this.store){
				console.warn("Pagination requires a store to operate.");
				return;
			}
....
就正常了。

**Comment by kfranqueiro** [comment]
RE the original post about duplicate refresh calls: as pointed out by @xiaohulu, you should not mix `Pagination` into `OnDemandList`, which is likely causing the problem.  You should mix Pagination straight into `dgrid/Grid` instead.

RE defining column widths, the `width` property in column definitions is only supported by the `ColumnResizer` extension, intended for use cases which require programmatically preserving/restoring column widths.  Otherwise, you should really be setting widths in CSS using `.field-<fieldname>` classes (e.g. `.field-name` or `.field-url` for the above example).
