### ISSUE TITLE
Tree expando double (and more) render

### ISSUE THREAD

**Issue by EToreo** [SitePen/dgrid#1059]
If the columns are defined in the mixin of a Tree grid then the expando icon gets rendered once for every tree that is instantiated based off that mixin.
A reproduction of this bug can be found here:
http://jsfiddle.net/4tagrntb/2/

A work around is to define the columns in the constructor.

I think this bug is caused by the way _configureTreeColumn "saves off" the default renderExpando function.

**Comment by kfranqueiro** [comment]
I'm closing this, since the "workaround" noted in the fiddle is essentially the correct approach, as also noted in dgrid's [Limitations](https://github.com/SitePen/dgrid/blob/v0.4.0/doc/usage/Limitations.md#reuse-of-column-definitions).

It might be worth noting that a slightly related issue which could end up leading to duplicate expand icons is being addressed in #1185.
