### ISSUE TITLE
couple of things

### ISSUE THREAD

**Issue by mc007** [SitePen/dgrid#1060]
Hi,

1. it would be great if you could make the use of xstyle as conditional feature, it takes a while to remove this dependencies after each dgrid update, and actually, it doesn't make quite sense to pull so much code for adding css stuff. in our apps that's done somewhere else. however, just saying, that would be great. of course, has-class is useful but it could be just a static util function somewhere. Also I am trying to replace put with jQuery, some tests showed, its just faster.

2. the other thing which drove me nuts is the 'replication' of a store(dstore as collection), it took me hours to figure out why my shared store-instance has suddenly altered properties, i had to put them in a object to hide them due to the replication, just saying that this could be noted somewhere more visible. 

3. btw, i experimented with a DCL based version of dgrid and the profiler results showed thousands of less calls compared compared with the classic Dojo composer, that makes dgrid working better on low-spec devices, just to let you know (i am aware about user needs and most used Dojo version..)...just saying.

thank you for this great lib!

**Comment by kfranqueiro** [comment]
> it would be great if you could make the use of xstyle as conditional feature, it takes a while to remove this dependencies after each dgrid update, and actually, it doesn't make quite sense to pull so much code for adding css stuff. in our apps that's done somewhere else. however, just saying, that would be great. of course, has-class is useful but it could be just a static util function somewhere. Also I am trying to replace put with jQuery, some tests showed, its just faster.

I had started experimenting with using `dojo/dom-construct` in place of `put-selector` around the end of last year, and was surprised to see it actually performed visibly better particularly in IE11.  I've just merged a bunch of changes to master which pull out put-selector and xstyle and use Stylus for organizing the structural CSS and skins.  All you need to do differently is load `dgrid.css` yourself.

That being said, xstyle wasn't really adding too much weight to dgrid, given that dgrid was only using 3 or so modules from it.

> the other thing which drove me nuts is the 'replication' of a store(dstore as collection), it took me hours to figure out why my shared store-instance has suddenly altered properties, i had to put them in a object to hide them due to the replication, just saying that this could be noted somewhere more visible. 

If this isn't well-represented in dstore's documentation or tutorials, I'd suggest entering a request on dstore's own issue tracker about this.

> btw, i experimented with a DCL based version of dgrid and the profiler results showed thousands of less calls compared compared with the classic Dojo composer, that makes dgrid working better on low-spec devices, just to let you know (i am aware about user needs and most used Dojo version..)...just saying.

Yeah, it's sometimes painfully apparent how expensive `this.inherited` in `dojo/_base/declare` can get (go look at the number of calls involved in a Dijit widget like FilteringSelect sometime...  you might have a heart attack).  That said, we're planning to evaluate the right direction to go for inheritance and mixins in Dojo 2, and I'm waiting on that discussion/decision before dgrid makes the jump.

I seem to recall that initially, there may have actually some thought of implementing dgrid using [ComposeJS](https://github.com/kriszyp/compose).  Perhaps Dylan or Kris could remember the details better than I could; I expect we ultimately went with `declare` because it fit the existing ecosystem better (and is what developers were used to) at the time.

**Comment by mc007** [comment]
right, re-performance: i don't mind at all what's good/bad for the developer on the coding side, but I do when it comes to performance (good code must be ugly :-). I found recently this here: http://jsperf.com/js-inheritance-performance/36. It might worth to check it for dcl over compose. The choice is pretty important given the fact how many stuff is built upon (dom-class seems to be the most redundant, upon inherited calls).However, this layer could break device coverage for Dojo/Dgrid apps on low-end devices (Beagle-Board/Raspberry PI,..) with mini-screens (room/building terminals) or the new TVs (currently just awful with dgrid/dojo).  just saying. I figured out that calling this._doBaseClassMethod in the subclass as much as possible always wins.
guenter

**Comment by bryanforbes** [comment]
I want comment here and caution against using [micro-benchmarks](http://mrale.ph/blog/2012/12/15/microbenchmarks-fairy-tale.html) to decide on an inheritance library. I want to especially caution against using something like jsperf to do this since previous benchmarks can change how the entire VM performs for subsequent benchmarks (for instance, calling `delete` on `Object.prototype` or some other base object would move all objects into a slower hash lookup on V8).

**Comment by mc007** [comment]
good to know, thank you Bryan. Then back to classic profiling and counting calls :-)
