### ISSUE TITLE
error when rendering collection with no items

### ISSUE THREAD

**Issue by neonstalwart** [SitePen/dgrid#1065]
i hit an edge case and don't have time to change course for a test case right now, but here's the description and feel free to bug me towards the end of the month for a test case if you are unable to reproduce.

```
grid.set({
    columns: startingColumns,
    collection: startingCollection
});
grid.set({
    columns: newColumns
    collection: emptyCollection
});
```

this causes an error at https://github.com/SitePen/dgrid/blob/94aeb547652b4aa8fdf0c0097e52817951bf45bc/OnDemandList.js#L184 because `parentNode` is `null`.  

i believe `preloadNode` is removed as part of https://github.com/SitePen/dgrid/blob/94aeb547652b4aa8fdf0c0097e52817951bf45bc/List.js#L374 which causes the problem.

**Comment by kfranqueiro** [comment]
I tried reproducing this out of curiosity but couldn't, but maybe I missed something since it's late and I'm tired.

I started http://jsfiddle.net/kfranqueiro/zz4mLw73/ if you want to try to get it to cause your issue.

**Comment by neonstalwart** [comment]
thanks for the starting point. I'll try to see if I get some time to work with it. I made a jsfiddle somewhere in the past month or so that stubs a Rest store and I believe that the issue may only appear when the store is async so hopefully I can easily combine that fiddle with yours and maybe then it will demonstrate the issue.

**Comment by neonstalwart** [comment]
note to self for later... http://jsfiddle.net/neonstalwart/w20uztfg/

**Comment by neonstalwart** [comment]
@kfranqueiro i believe this demonstrates it http://jsfiddle.net/neonstalwart/36vsxdL9/

**Comment by kfranqueiro** [comment]
Thanks for that test case.  I suspected it may require an async store about an hour after I posted last night; I am now able to reproduce this with `createAsyncStore` as well.

At this point I'm pretty sure the problem is basically that it's trying to place the `noDataNode` for a previous promise resolution, after a subsequent refresh has already happened, so the `preloadNode` is totally stale (refreshing creates new ones).

Ostensibly the same problem could affect the rendering of actual results, except that we are preventing it in `List.js` by checking whether the container we're about to attempt inserting into actually exists.  Clearly that's not exactly ideal either.

In the long run we should probably consider outright canceling any outstanding requests when a new `refresh` happens, but I'm a little wary of edge cases there - as well as the fact that any canceled promises end up barfing in the console (which, while we know well enough to ignore in the case of CancelErrors, I am sure that some people would complain about on principle).

I am going to look into a short-term solution for now.  I expect this is also reproducible in 0.3 and we'd like to do one more 0.3.x release soon, so I'd like to fix this for that too.  I am hoping for us to clean up OnDemandList as a whole for the next major release anyway, so it makes sense to look at the long-term solution then.

**Comment by neonstalwart** [comment]
cool - i'm sure you realize that the refresh is happening in response to setting the columns and the outstanding promise is in response to setting the collection.  i'm not sure i'd want to cancel the promise in that case.  

i could set the columns first (and that's what i've done to work around this) but i was concerned about the possibility of the grid unnecessarily trying to somehow fetch data from the previous collection and trying to display it through the new columns (had not looked into if that would actually happen).

**Comment by kfranqueiro** [comment]
> cool - i'm sure you realize that the refresh is happening in response to setting the columns and the outstanding promise is in response to setting the collection.  i'm not sure i'd want to cancel the promise in that case.  

Yes, that's what's happening, and I don't think that canceling would be a problem in that case since the new collection would have been set, so the second refresh from setting the columns is also requesting from the new collection.  (The fact that we are requesting twice is in itself also not ideal, and I believe that issue has been raised separately.)

> i could set the columns first (and that's what i've done to work around this) but i was concerned about the possibility of the grid unnecessarily trying to somehow fetch data from the previous collection and trying to display it through the new columns (had not looked into if that would actually happen).

I believe this is what I explained in my last comment - the display shouldn't get confused, because of https://github.com/SitePen/dgrid/blob/v0.4.0/List.js#L442 (in combination with the fact that OnDemandList's preload nodes are completely replaced on every refresh).
