### ISSUE TITLE
dgrid doesn't work when it created in invisible DIV

### ISSUE THREAD

**Issue by akaJes** [SitePen/dgrid#1082]
just add before grid creation
document.body.style.display='none'
and after
document.body.style.display='block';

symptoms:
1. header can disappear
2. scrolling can work improperly (ondemand,rest)
3. rows can disappear
and etc.

tested on 4.0

**Comment by kfranqueiro** [comment]
Can you provide code that reproduces the issue?  You shouldn't experience issues like this unless you are explicitly calling `startup` while the grid's DOM is not in document flow (and `startup` should never be called before a widget's DOM is in flow, that's kind of the point).

**Comment by akaJes** [comment]
I just open from tests folder Rest.html and wrap grid cretion code with code, that described in first post.
Like this:

document.body.style.display='none'

window.grid = new CustomGrid({
						collection: createStore().getRootCollection(),
						sort: "id",
						getBeforePut: false,
						columns: getColumns()
					}, "grid");
					new CustomGrid({
						collection: createStore({useRangeHeaders: true}).getRootCollection(),
						sort: "id",
						getBeforePut: false,
						columns: getColumns()
					}, "gridRangeHeaders");

document.body.style.display='block';

In my huge code this issue i cant remove with 'startup' manipulation
But when call 'refresh' of grid after it became visible in first time some bugs disappering

**Comment by akaJes** [comment]
I think,that  this issue caused when DOM objects used in the dgrid are invisible and dont have dimensions, but it used for calculating internal variables and grid's drawing results are unpredictable

**Comment by kfranqueiro** [comment]
If I do what you described in your second post, the grids in question won't have any rows rendered because `startup` won't be called at all (dgrid normally calls `startup` automatically if the widget is already in flow).  That's the reverse problem of what you're describing.

What you are describing in your first and last comments sounds precisely like what happens if you tell the grid to `startup` or `resize` (the former also calls the latter) when its DOM node is not in document flow.  Calling `resize` again once it is actually in flow tends to resolve the issue, but the correct solution is to only call `startup` at a point in time where the grid's DOM node is already in document flow.

This is *by definition* how the `startup` function is intended to behave and be used.  When you are calling `startup`, you are telling the widget, "your DOM has dimensions now, do any final creation lifecycle tasks that you need dimensions for now."  If the widget's DOM isn't actually in flow when you call this, then you're basically lying to the API and can expect wonky results.

**Comment by akaJes** [comment]
I understood , that is imposible to control from Widget
Just i must append <code>startup</code> code to my events witch make visible tabs(not dojo) with created DGrid widgets

thx a lot
