### ISSUE TITLE
Grunt build conflicts with Dojo build

### ISSUE THREAD

**Issue by aprilmay** [SitePen/dgrid#1095]
The Dojo builder was failing after trying to automatize the application building process from sources.

Summary of the process:
1/ Build dgrid css files with grunt
- dgrid building depends on grunt and modules (stylus)
- these grunt modules must be installed using 'npm install' with the '--save-deps' option (see also: https://github.com/gruntjs/grunt/pull/976)
- npm creates a directory node_modules in the dgrid directory
- one cannot move node_modules because grunt requires it locally

2/ Build dojo
The build fails (ReferenceError: alert is not defined), because the Dojo builder scans the node_modules.

A simple work around: move manually the node_modules directory out of the grid directory before building Dojo.

A more streamlined process would be nice to have.
One option: mark the node_modules directory explicitly excluded from the build in package.js.
Better option: have grunt using the globally defined npm modules path, but it's not clear to me wether it's possible or not.

Or, maybe i missed another obvious thing? I'm feeling a noob here :)

**Comment by dylans** [comment]
This is actually also a problem with dojo core if you install Intern to run the tests. I think we probably need to go through our default package build profiles and add a regex to exclude node_modules.

**Comment by kfranqueiro** [comment]
Yeah, I ran into this too both with dgrid and dstore.  Definitely annoying, definitely would be good to solve.

**Comment by kfranqueiro** [comment]
This can be resolved for typical builds by updating the `miniExclude` resource tag in `dgrid/package.js` to return `true` for files under `node_modules`.  (I say typical builds because if you override the default and set `mini: false`, you'd run into the same and more issues, unless we also added this and more things to the `copyOnly` resource tag too.  I'm not aware of a way within package configuration for the build system to tell it to never, ever, look at / copy particular files...)

I'd like to understand your use case though - normally I wouldn't expect anyone to run into this under normal dgrid usage (i.e. I wouldn't expect normal use to entail running `npm install` inside dgrid for its `devDependencies`).  Can you explain what your workflow is?

**Comment by aprilmay** [comment]
I'm not sure i understand your question correctly.
Basically my workflow is: update the sources of the various components and build through Makefiles.

I'm not interested in devDependencies as such, i just want to have a working, up to date dgrid. Maybe the "--save-deps" option is superfluous, what i really observed is that installing the node modules globally (-g) doesn't work with "grunt stylus".

**Comment by kfranqueiro** [comment]
Having a working, up to date dgrid doesn't require installing any of its npm dependencies.  The CSS files are included in the repository as well as the stylus files, and if you are intending on building specific parts of the stylus yourself, I'd typically expect you to have your own styles and node_modules somewhere outside the dgrid package.  (I haven't thought about excluding CSS from the repo yet because it _would_ add complexity either to consuming or producing dgrid releases.)

That's why I'm trying to understand how you ended up running into this issue, since it requires having `npm install`ed *inside* the dgrid folder, which generally is only necessary when actually maintaining dgrid itself.  While this issue can be "resolved" for dgrid's package as I stated earlier, it isn't something that would normally be encountered.

**Comment by kitsonk** [comment]
No further response after @kfranqueiro feedback, so closing for now.
