### ISSUE TITLE
InputListener change event for Editor does not pass column to handler

### ISSUE THREAD

**Issue by schallm** [SitePen/dgrid#1113]
The column variable is not provided when calling _handleEditorChange in the main InputHandler within Editor.js (version 0.4):

    this.on('change', function (evt) {
         self._handleEditorChange(evt);
    });

The column is already available and is passed in the IE specific events.  It should look like the following:

    this.on('change', function (evt) {
         self._handleEditorChange(evt, column);
    });

**Comment by kfranqueiro** [comment]
This won't actually work, because this code registers a single delegated event listener for the entire grid - not one per column.  The old-IE case is special in that it is registering event handlers on each individual input.

The code in `_handleEditorChange` already looks up the column itself from the event target, so the old-IE branch passing `column` is really just a shortcut to avoid that overhead when it's already known.
