### ISSUE TITLE
How to disable checkbox in selector in dgrid 0.4?

### ISSUE THREAD

**Issue by dhananjaylokhande43** [SitePen/dgrid#1127]
We are migrating from dgrid 0.3 to 0.4 and facing starnge issue related to disabling checkbox based on business logic in dgrid.

```js
 _getGridCols: function() {
                return {
                    selectorCol: {
                        label: " ",
                        selector: "checkbox",
                        disabled:lang.hitch(this, this._canSelectProduct)
                    }
}
```

`_canSelectProduct` is private method which has business logic and based on it, it returns flag.
But problem observed is, this private mathod don't get called at all with dstore. Only static data getting coming from service get applied to screen. There are other columns which we dont want to disable so can't use 'allowSelect' option so kindly suggest any solution if you have, thanks

**Comment by kfranqueiro** [comment]
The `disabled` property of selector columns was removed because it was ultimately redundant of the `allowSelect` method on grids with the Selection mixin (both controlled the same thing, in opposite directions).  It's listed the Removed APIs section of the [0.4.0 Release Notes](https://github.com/SitePen/dgrid/releases/tag/v0.4.0).

`Selection#allowSelect` receives a row object (with `id`, `data`, and `element` properties) and should return `true` if selection (and any selector) for that row should be enabled, or `false` if it should be disabled.

**Comment by dhananjaylokhande43** [comment]
Would you please share some example with Selection#allowSelect , how it is used. We don't want to disable whole row. from row, only one column which has checkbox and there are other columns who needs to be enabled at the same time. Kindly advise.

**Comment by kitsonk** [comment]
It is better to ask questions on [Stack Overflow](http://stackoverflow.com/questions/tagged/dgrid).  You are more likely to get an answer as well as it allows us to keep the focus of the issues here as actual issues with the project.  Thank you.
