### ISSUE TITLE
Auto adjust column width to content

### ISSUE THREAD

**Issue by jvegaseg** [SitePen/dgrid#1129]
Is it possible to create a grid where the width of each column be calculated automatically to the width of the column content? With html tables is very easy but with dgrid I can not get any results.

I was googling but nobody gives a solution. If it is possible, please, let me know how to do it.

Regards,

**Comment by kfranqueiro** [comment]
This would require expensive operations to measure the widths of the content in each cell and then apply CSS rules to adjust column widths.  We've had to do it at least once for a project - it wasn't very pretty, and it could get very slow particularly in IE8 - more due to adding CSS rules than due to the dimension measurements themselves.

The reason it requires this much work is because dgrid (and pretty much all dojo-based data grids, for that matter) render each *row* as its own div containing a table - it's not all one table.  This is done for various reasons, including keeping the header fixed, and enabling advanced features like virtual scrolling and hierarchical display.

Moreover, this idea would be entirely incompatible with `OnDemandGrid` (lazy loading / virtual scrolling), given that it only displays a certain range at a time.  For this idea to make sense, you'd really need to have all of the data visible.  It'd be feasible with `Pagination` if you're okay with the columns resizing every time `gotoPage` is called.
