### ISSUE TITLE
Support .placeAt(node, pos) 

### ISSUE THREAD

**Issue by gavinr** [SitePen/dgrid#1135]
Similar to other dijits, allow me to place my dgrid in the form:

```
this.myGrid = new CustomGrid({ ... });
this.myGrid.placeAt(myNode, 'last');
```

**Comment by kfranqueiro** [comment]
I just pushed a commit to a branch that adds this, if you want to take a look at the diff and apply it yourself for now.  I want to have unit tests for it before merging it.

**Comment by dylans** [comment]
I think one of the reasons this wasn't included before was the perception that _WidgetBase was pretty large in size, though perhaps that has changed now? It might be worth making it a separate extension if it is fairly large, though most apps that use dgrid probably include _WidgetBase anyway. It's probably worth comparing build sizes?

**Comment by kfranqueiro** [comment]
Funny you mention that.  I had some thoughts hit me in the last hour that might explain why this wasn't added earlier.

* It's quite possible that at the time we first thought about this, the `DijitRegistry` extension didn't exist.  Notice that's where I added this - it's pretty safe to assume that if you're using that extension, you're already loading `_WidgetBase` anyway.
* On top of not wanting this in `dgrid/List` directly due to `_WidgetBase`, there is (or was, up through/including 0.4.x) the fact that dgrid didn't use `dojo/dom-construct`, it used `put-selector/put`.  Even implementing just the DOM parts of `placeAt` directly would've involved bringing in a module that was otherwise redundant at the time.

We could potentially consider putting the DOM-specific part of this directly in `dgrid/List` in master (which no longer relies on put-selector), and the widget portion of it (perhaps still leaning on `_WidgetBase` directly in non-DOM cases) in the `DijitRegistry` extension.  But I wouldn't want to do that in 0.4, and it might be confusing (1) separating it to 2 places and (2) changing it between 0.4 and master, so I'm inclined to keep it simple the way I currently added it above, which only exposes it through the `DijitRegistry` extension.

**Comment by kfranqueiro** [comment]
Since this didn't get any further comments, I've gone ahead and added tests to my previous commit and merged it.  This will be in 0.5.0 and 0.4.1.

**Comment by gavinr** [comment]
Thanks @kfranqueiro !
