### ISSUE TITLE
Editor dgrid-datachange event fires when it shouldn't.

### ISSUE THREAD

**Issue by gsexton** [SitePen/dgrid#1142]
According to the documentation for Editor:

"The Editor mixin emits a dgrid-datachange event whenever an editor field loses focus after its value is changed. "

However, if you set the input type number, and use the browser supplied widget (e.g. up/down arrows) to alter the value, the dgrid-datachange event fires each time the value is changed, and not just when focus is lost.

I've tested and can reproduce this issue in the current versions of Firefox and Chrome.

**Comment by kfranqueiro** [comment]
Thanks for reporting this.  The issue here is that the documentation's explanation was perhaps a tad oversimplified.  When native form inputs are used, Editor listens to their `change` event.  In some cases this generally coincides with when the component is blurred, but not in the case you mentioned.  I've updated the docs to be more specific/accurate.
