### ISSUE TITLE
Check Box Click value will not be saved if focus is on textbox or number text box editor !!

### ISSUE THREAD

**Issue by shahzad31** [SitePen/dgrid#1169]
Steps to reproduce !!
try visiting this page 
http://dgrid.io/js/dgrid/test/Editor_autosave.html
Change some value 3rd Column , and don't click any where else, try clicking checkbox widget in 4th column, it will not be clicked as focus was on number. Same behavior can be observed for text Box.
if you are editing textbox in dgrid editor and simultaneously without leaving focus if you try to click checkbox, it does seems like it got clicked but it's value will not be propagated in dgrid store.

**Comment by kfranqueiro** [comment]
This also occurs with the native checkbox in the last column.  Also, if you look closely and hold the mouse button down, you'll notice that the row refreshes as soon as you press the mouse button on the checkbox.

So I think what's happening is that the 3rd column is triggering autosave as soon as it is blurred (as soon as the mousedown occurs elsewhere), and thus the click on the checkbox never even registers (because the entire row is redrawn before mouseup happens).

Given that `autoSave` is technically behaving as designed, I'm kind of wondering what we would do about this.  Recently I brainstormed a rudimentary mixin to allow re-rendering only specific cells rather than the entire row, and that might help to resolve this.  I should probably think about making that a thing in 0.5 and seeing how we can take advantage of it.

**Comment by shahzad31** [comment]
Probably no one needs this anymore.
