### ISSUE TITLE
save() of _StoreMixin havent _trackError call

### ISSUE THREAD

**Issue by akaJes** [SitePen/dgrid#1196]
<code>grid.save()</code> don't process a common error checking and <code>drid-error</code> invoking
but using
<code>grid._trackError('save')</code> instead <code>grid.save()</code> provide a common checking and it is not a public interface call and not described
or using <code>grid.save().then(null,fail_function)</code> is an additional code and can be missed

**Comment by kfranqueiro** [comment]
`_trackError` is generally geared toward instances where the developer wouldn't otherwise have any way to handle errors (for example, as a result of direct user interaction with the grid).  In these cases, `_trackError` is used to provide a hook for error handling via `dgrid-error` events.

In the case of `_StoreMixin#save`, this is a public API which a developer would call directly, and as a result, they have direct access to the promise it returns, which already provides a mechanism for handling errors (through the error callback, as you stated), so it makes less sense to run through `_trackError` (since that would capture the rejection itself and emit `dgrid-error` instead).

So in this case what you've observed is intentional.  Thanks for lending a keen set of eyes, though. :)  I think we can improve the wording in the `save` docs a bit anyway, so I'll see about specifically mentioning rejection in there so people hopefully don't forget about that as you mentioned.
