### ISSUE TITLE
Make dgrid 0.4 available on NPM

### ISSUE THREAD

**Issue by kitsonk** [SitePen/dgrid#1200]
We should find a way to publish dgrid 0.4 on NPM.

**Comment by kfranqueiro** [comment]
Can you explain how this would actually be used?

I should probably also point out that dijit and dojox aren't even on npm properly.  (It seems like someone registered dijit and dojox, but...they don't seem to actually work at all.)

**Comment by kitsonk** [comment]
@dylans could you give your vision behind this request?

**Comment by dylans** [comment]
Yes, some people want to use npm as their general purpose package manager to just grab all of the JS code they use, even if it doesn't really make sense.

Not making it possible to quickly grab copies of code via npm and bower just slows adoption, whether we think it makes sense or not.

**Comment by kfranqueiro** [comment]
> Not making it possible to quickly grab copies of code via npm and bower just slows adoption

It's already doable via bower, so this sounds a little weird.  We have [very straightforward instructions](https://github.com/SitePen/dgrid#installing-with-bower) to do this.  The only thing you might have to do in advance is `npm install -g bower`, which, lookit that, uses `npm`. :D

> whether we think it makes sense or not.

It's one thing whether we think it makes sense; it's another if I can't even envision *how* they'd be using it, which is why I asked how it would actually be used.  The way I see it, usage would range somewhere between unnecessarily cumbersome to downright infeasible:

* Are they just going to use npm as an awkward package fetcher, then use dgrid as normal but need to jump through hoops to configure their AMD loader?
  * This could easily lead to an increase in "bugs" and questions asked because we are suddenly exposed to people who picked the least sensible installation mechanism and now have painted themselves in a corner they don't know how to configure their way out of.
* Or are you thinking in terms of browserify?  This might be completely unrealistic, because:
  * Browserify seems tailored to creating a bundle with a single entry point, whereas every single dgrid module is intended to be directly accessible for composability
  * You would likely need to de-AMD-ify dgrid to accomplish this, which is not very feasible due to reliance on AMD loader plugins

Either way, this seems to be adding maintenance overhead for us for no clear benefit, because there is already a rather widely-adopted installation mechanism that Just Works.  We've been stretched thin enough already on maintenance time for dgrid this year; we don't need to be opening a new shiny can of worms when we're already up to our ears in worms from previously-opened cans.  It would not be anywhere near the top of my priority list.

**Comment by kfranqueiro** [comment]
Ultimately, we've decided to publish dgrid 1.1.0 on npm.  I've added documentation about the caveats, and an `.npmignore`.

This was done more out of necessity after recovering the `dgrid` package from someone who was meaninglessly squatting it, than anything else.  Bower remains the preferred installation method.
