### ISSUE TITLE
Shift click with multiple selection behaves awkwardly in Edge

### ISSUE THREAD

**Issue by maier49** [SitePen/dgrid#1203]
In Edge, if shift + click is used in Edge, the browser also highlights all the text from the last focused element outside of the grid body to the point that was shift clicked. This can be easily replicated in the OnDemand test page for dgrid. Simply click text outside of a grid, or a header, then click a row in the grid and shift click another row. This behavior can be avoided by calling `preventDefault` on the event, but I don't know what kind of unintended side effects that might have.

**Comment by kitsonk** [comment]
The current version of dgrid wasn't designed to work with Microsoft Edge, so labelling this as an enhancement.

**Comment by kfranqueiro** [comment]
I intend for us to fix any Edge bugs we discover prior to tagging any new releases.  How it's labeled here doesn't really matter to me :)

**Comment by kfranqueiro** [comment]
I looked at Bradley's PR, but digging further into this issue, I'm realizing that Edge is not going down the same code path as IE because Edge defines `webkitUserSelect` in addition to `msUserSelect` which throws the feature-detection code off.  So while the PR fixes it, I think there might be a more appropriate solution.

I also suspect we may be able to yank out a bunch of code from `Selection.js` provided we require Dojo >= 1.8.2 (currently it's set up to require >= 1.8.9 anyway), but we're going to need to re-test every browser if we do that.

Gotta love it when we don't UA sniff because of how browsers cheat the UA string...and then a browser goes and cheats something else that makes feature detection just as brittle.

**Comment by kfranqueiro** [comment]
Oh right. I should also mention that dgrid's `css-user-select` has feature is colliding (and losing) to `dojo/dom`'s (which I added myself), and the two implementations have somewhat diverged.  This is part of the code I was referring to "yanking out" in my previous comment, and we're probably better off doing so to prevent future confusion, though it may be an inconvenience to anyone who happens to be using dgrid 0.4 with Dojo 1.8.0 or 1.8.1 (but realistically nobody should be using those versions anyway; IIRC there were some pretty major issues prior to 1.8.3).

**Comment by kfranqueiro** [comment]
Currently running automated tests over an alternate fix, which I've already verified manually: https://github.com/kfranqueiro/dgrid/commit/7211f6d3f261bd98fd35ff1e62b22b5ac0cdf65a
