### ISSUE TITLE
Tree Not rendering the expansion as per parent-child relationship and collapseOnRefresh property is not working.

### ISSUE THREAD

**Issue by lakshay1994** [SitePen/dgrid#1244]
When **Tree** is created, all the children are by default expanded in an order which is not expected as per the defined parent and children relationship of the objects. The issue is represented in the fiddle, a tree having single column with well defined parent-child relationship and `CollapseOnRefresh` property set to true. Even after this tree is not behaving accurately.

All the directories and sub- directories need to be clicked twice in order to arrange the objects in correct order.

Fiddle- [Here](https://fiddle.jshell.net/lakshay94/zv7d0ohb/14/)

**Comment by kfranqueiro** [comment]
Your Fiddle is missing 2 things:

* The default implementation in `dstore/Tree` expects top-level items to explicitly have `parent: null`
* When you assign a collection to the grid, you should be assigning `store.getRootCollection()`, not just `store` (which won't filter children at all)

https://fiddle.jshell.net/zv7d0ohb/15/ (I also updated script/style references since the original was failing to load dojo and dgrid for me)

This is discussed in the [0.4 migration guide](https://github.com/SitePen/dgrid/blob/v1.0.0/doc/migrating/0.4-Migration.md#dgrid-04-and-the-dstore-api).

**Comment by gaurav21r** [comment]
@kfranqueiro Thanks for resolving this. Don't you think its counter intuitive to have a `null` set on all the root elements? Can't the code in dStore just check for the existence of `parent` property? 

If you agree, I'd be happy to create a PR at dStore repo. I saw this https://github.com/SitePen/dstore/blob/master/src/Tree.js#L39 to be a simple call to `filter()` so I guess code (if you agree) is to be changed in `filter()`?
