### ISSUE TITLE
Possible rowHeight regression in 0.4.1

### ISSUE THREAD

**Issue by dmartinzar** [SitePen/dgrid#1251]
The following example used to work properly with version 0.4.0. In version 0.4.1, the grid renders only the initial 25 rows and refuses to render the remaining rows until after another refresh:

Reproduction: http://jsfiddle.net/qracfw2q/1/

I say "Possible" in the title because it is unclear to me whether this was an officially supported use-case. Other Dijit widgets (such as ContentPane widgets) can safely have their `startup()` method called once they are placed in the page, but not necessarily visible yet (as is the case with tabs). dgrid now seems to require that the grid both be in the page _and_ completely visible before `startup()` is called, otherwise the `rowHeight` property is not calculated correctly and the preload node is not setup at all. This indicates that it is no longer safe to call `grid.startup()` within the content pane's `startup()` method.

I've identified two different work-arounds in 0.4.1:

1. Set `rowHeight: 22` on the grid instance to emulate the behavior in 0.4.0. This effectively undoes 6163f3eb12bf49f9c4e2d22cb8a41426c14655e0.
1. Delay `startup()` on the grid until its parent pane is shown (http://jsfiddle.net/qracfw2q/2/):

        self.own(self.on('show', function () {
            self.grid.startup();
        }));

Should dgrid allow `startup()` to be called during the normal Dijit startup chain? If so, what needs to change to get `rowHeight` recalculated at the correct time? Maybe some code in `DijitRegistry` that watches for the `show` event on the parent widget?

**Comment by kfranqueiro** [comment]
`startup` is intended to only be called when the widget is in document flow.  Therefore, I'd say this case wasn't intended to work (and I would suspect it fell into exactly the bug that the commit you pointed out is designed to prevent, where it would end up rendering all rows immediately).

I suspect something's amiss in your widget hierarchy, since this sort of thing [just works](http://dgrid.io/js/dgrid/test/dijit_layout.html) when a grid with `DijitRegistry` mixed in is made a direct child of a layout container widget (which normally calls `startup` on its children when they are first displayed, provided the parent layout container itself has been started up).

However, this potentially points out that the fix to that was kind of sub-optimal, since it somewhat irreversibly slams on the brakes.

**Comment by dmartinzar** [comment]
I did a little more investigation. The grid in the jsfiddle reproduction _is_ in the document flow when `startup` is called. The issue appears to be that the second tab, and therefore the grid child, has no height at that time, so `grid.domNode.offsetHeight == 0`. After the tab is shown, the grid correctly resizes to fill the entire tab.

In your working test case where the grid is a direct child of the tab container, the grid has a non-zero height when `startup` is called, so `rowHeight` ends up non-zero. Sure enough, if I update the jsfiddle to construct the grid declaratively as the direct child of the tab container, the issue goes away.

Now I have a few more questions:

1. Why is the height of the tab/grid 0 in one case and not in the other?
1. Should dgrid support `startup` being called when it has no measurable height?
1. If not, what needs to be done to `GridPane` in the jsfiddle above to have it correctly render its dgrid child widget?

**Comment by kfranqueiro** [comment]
I dug into this more today, and concluded that...dijit breaks its own rules when it comes to `startup` and derivatives of `StackContainer`.

Ostensibly, `startup` is *supposed* to only be called when the widget's element is in document flow, but that's most certainly not the case for inactive children of StackContainers, and yet it seems as if that still goes through `_WidgetBase`'s `startup` code which blindly runs it on all children.  I dearly hope I am missing something, but everywhere I tested - even in Dojo 1.6 (where that logic was in `_Container`, IIRC) - that seemed to be the case.

However, these container widgets sort of squeak by because they do still call `resize` whenever a child is selected/shown.

Given what I had already concluded before about that earlier commit to dgrid perhaps slamming on the brakes a bit too hard, I've got a [branch](https://github.com/kfranqueiro/dgrid/tree/1251-rowHeight-resize) with an attempt at resolving this.  It seems to resolve your fiddle, which I've [updated](http://jsfiddle.net/qracfw2q/3/) to test using the branch.

**Comment by kfranqueiro** [comment]
Someone on the mailing list happened to run into this same issue and my changeset resolved it for them.  I'm going to run some tests and merge it.

**Comment by dmartinzar** [comment]
Awesome! Thanks Ken.
