### ISSUE TITLE
DGrid doesn't render nicely inside ContentPane or TitlePane

### ISSUE THREAD

**Issue by bartverweire** [SitePen/dgrid#1274]
Hello,

I'm starting to integrate dgrid into my application, which heavily relies on nested layout elements like LayoutContainers, ContentPanes and TitlePanes.
Even in a very simple test case, I can see that dgrid doesn't render nicely inside a ContentPane or TitlePane.
This is because the ContentPane by default has a padding, which I would like to keep.
In a default ContentPane, the header is left aligned with the border ContentPane, disrespecting the padding.
If I modify the css like
		.dijitContentPane .dgrid-header-row {
			left: 8px;
		}
		
		.play_with_css.dijitContentPane .dgrid-scroller {
			top: 8px;
		}
The header aligns well, but the header columns are slightly smaller than the normal columns.

Uploaded a test html file (as test.txt) with a modified version of the Hello dgrid page.

[test.txt](https://github.com/SitePen/dgrid/files/222172/test.txt)

Regards,

Bart

**Comment by kfranqueiro** [comment]
There are a couple of oddities in your example which I can immediately identify.

1. You probably want to consider mixing in dgrid's [DijitRegistry extension](https://github.com/SitePen/dgrid/blob/v1.0.0/doc/components/extensions/DijitRegistry.md) for better compatibility with dijit layout widgets.
2. Your code is creating dgrid instances that will "clobber" your ContentPanes, replacing their `domNode` with each grid's own.  This becomes more immediately noticeable upon mixing in `DijitRegistry` since then dijit will complain about duplicate IDs being registered.
3. It's not entirely clear from the reduced example what your ultimate goal is, but dgrid instances using `DijitRegistry` do not need intermediate ContentPanes in order to be placed within layout containers such as BorderContainer and StackContainer. If you're ultimately looking to place grids in layout containers, you may not need ContentPanes at all.

Given that this is more of a usage question than a dgrid bug, I'm closing this and would suggest posting a question on [StackOverflow](http://stackoverflow.com/questions/tagged/dgrid) if you still have questions after trying the advice above.  Thanks!
