### ISSUE TITLE
scroll to selected row using onDemandGrid 

### ISSUE THREAD

**Issue by gtejaswi** [SitePen/dgrid#1284]
Hi, 
I am trying to scroll to a selected row on dgrid view. The row is selected using rowID , I am able to scroll to the view, working with a store of small set of data.
var row = dgrid.row(rowID);
dgrid.select(rowID);
row.element.scrollIntoView();

However i am facing issues scrolling to the selected row in the following scenario. 
If the store holds larger set of data like hundreds of rows, I am trying to select a row very deep in the list and scroll to the view of selected row.  I am seeing a error that the row.element is undefined. 

I am currently using onDemanGrid along with dojo/store. I am wondering why is the element undefined when the store actually have it. Does using onDemandGrid causing the element to be not rendered. What could be the workaround for this issue ?

**Comment by zub2** [comment]
OnDemandList/Grid only render the visible elements + some range around. If you're getting undefined element from row() it means you're asking for a row that has not been rendered.

It's possible to tune how many elements are rendered and if elements that were rendered and then scrolled away from are deleted - see https://github.com/SitePen/dgrid/blob/master/doc/components/core-components/OnDemandList-and-OnDemandGrid.md#property-summary

If you need to have all rows available use Grid, not OnDemandGrid. OTOH if there are many items in the collection this would result in low performance.

If you want to scroll to an item that has not been rendered yet - see #1279. The dgrid authors don't see it as a good idea though.

**Comment by tejaswi17** [comment]
Thanks for the inputs. I am quite new to dgrid and I'am still confused with implementing above approaches ,

It seems i can limit maxRowsPerPage to 250 rows on page at a time, if i ask to select a deeper row and scroll dynamically, how would it work. Can you give me more insight of how i could implement this?

I understood that i can use scrollto by calculating row postion, but how would i know the index that i can use for y coordinate

**Comment by msssk** [comment]
> why is the element undefined

`OnDemandList` implements virtual scrolling, which means that only a subset of the data is rendered at any time.

> What could be the workaround for this issue

Think of the user interaction - what does the user need, how do they request it, how can you display it? Putting thousands of rows in front of a human is rarely useful. Filtering and pagination can present the user with a smaller amount of information that is easier to make sense of. If you know precisely what data you want to display, perhaps filtering the grid or even displaying the data nearby but outside the grid would be a good solution for the end-user.

Scrolling to a single row within hundreds or thousands requires exact precision. That precision is not available when the rows don't actually exist. Even in scenarios with uniform row heights it has proven difficult to reliably scroll to a specific row, which is why this functionality is not implemented in dgrid.
