### ISSUE TITLE
Resizing grid with column resizer resizes headers and not the grid...

### ISSUE THREAD

**Issue by moosepic** [SitePen/dgrid#1296]
Hi,

I've attached an image for this just to demonstrate the issue...  This is using the column resizer. The columns were given set widths.  If you resize the content pane containing the dgrid (a simple Grid with a Request store powering it). Even if the columns not given fixed widths this happens (the last column is set to auto expand), the headers and data stop lining up. If you do a sort on the data after, it fixes itself.

I've worked my way around it using event handling and firing resizes, but it isn't smooth (and really, it's a hack job)
![columnresizerissue](https://cloud.githubusercontent.com/assets/5174768/17057855/9037d808-4ff7-11e6-94f1-5a01cdebb2a3.png)

**Comment by edhager** [comment]
@moosepic, can you provide a simplified test case that demonstrates the problem?  You can paste code into this ticket or give a link to a working example on something like jsfiddle.net.

**Comment by PhanindraGIS** [comment]
Is there any solution for this, I am facing same issues.
I have added dgrid in one of the widget in my web Application. The grids columns header is resizing but not data when resizes the widget.

**Comment by msssk** [comment]
Are you experiencing this when the window is resized, or some DOM modifications are resizing a containing element?

dgrid (and Dojo/Dijit) were created well before [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) existed and continue to support some older browsers, so `ContentPane` and dgrid do not dynamically respond to DOM changes not caused by the viewport resizing.

When used within a `ContentPane` any call to `ContentPane.resize()` will be propagated down to dgrid. When used without `ContentPane` dgrid will listen to window resize events.

If you only need to support modern browsers you should be able to create your own `ResizeObserver` and use that to call `ContentPane.resize()` or `grid.resize()` as appropriate.

**Comment by PhanindraGIS** [comment]
I have already fixed the issues.  but forgot to update here.
As you mentioned above, grid.resize()  got worked for me.
