### ISSUE TITLE
dgrid column get allow to return a promise.

### ISSUE THREAD

**Issue by chickeaterbanana** [SitePen/dgrid#1307]
At the moment it isn't possible to return a promise in the get function. It would be great to be able to return a promise for nested queries.

`var grid = new BaseGrid({
  collection: xyz,
  columns: [
    {
         label: "first",
         get: function(object) {
              return wxyz.filter({
                                    id: object.nested_field_id
                                }).select("name").fetch().then(
                                    function(data){
                                        return data[0];
                                    });
         }
    }
  ]
});`

**Comment by msssk** [comment]
Managing asynchronous processes is very complicated and dgrid encapsulates that complexity in the `_StoreMixin` module. Introducing asynchronous behavior to other areas of the code, such as this, is not a good tradeoff for the added complexity. This scenario is better handled in the structure of the store data so that an asynchronous `get` is not required.
