### ISSUE TITLE
Error in the project, resources are not loading properly

### ISSUE THREAD

**Issue by siladitya006** [SitePen/dgrid#1332]
![image](https://cloud.githubusercontent.com/assets/16885291/21178461/b000f742-c215-11e6-8c7e-be3700691e78.png)

**Comment by websoftix** [comment]
Try load the demo using a http server (install one like XAMPP on your computer if you don't have), it should look like http://localhost/path/to/demo.

**Comment by dylans** [comment]
Agree with @websoftix , the issue is that you need to load it from a web server as file system access has reduced browser permissions (even if said web server is running on your local machine).  See [Why do I need to use an HTTP server with Dojo](https://www.sitepen.com/blog/2014/07/30/dojo-faq-why-do-i-need-to-use-an-http-server-with-dojo/).
