### ISSUE TITLE
Grid.js formatter uses innerHTML by default, facilitating injection vulnerabilities

### ISSUE THREAD

**Issue by mbomb007** [SitePen/dgrid#1419]
Grid.js lines 236 - 237:
`td.innerHTML = typeof formatter === 'string' && formatterScope ? formatterScope[formatter](value, object) : this.formatter(value, object);`

The code above makes it easy for programmers to create applications with script injection vulnerabilities. If the formatter function returns a dynamic string/property that contains malicious HTML/JavaScript content, it will be inserted into the DOM without a second thought.

It would be a better idea to make the attribute dynamic but default it to textContent. That way the user can set some property to change it to use innerHTML if dynamic HTML is desired. Something like this:

`td[this.allowHTML ? 'innerHTML' : 'textContent'] = typeof formatter === 'string' && formatterScope ? formatterScope[formatter](value, object) : this.formatter(value, object);`

**Comment by dylans** [comment]
I'd generally be ok with either suggestion, though I'd want a specific name for the property for the initial suggestion, e.g. `formatterAllowHTML` rather than `allowHTML`.

**Comment by schallm** [comment]
mbomb007 and I actually work at the same company and decided to move forward with "object with `html` property" approach since the decision to use html is part of the return statement and can't really be used accidentally by a developer.  

Is this something that you would like a pull request to "fix" dgrid?  It would be a breaking change if people are currently returning valid html from their formatter functions.  However, the change would be "safe by default".  Or would you like a pull request for the extension?

**Comment by schallm** [comment]
Added pull request https://github.com/SitePen/dgrid/pull/1422

**Comment by msssk** [comment]
Fixed in #1422
