### ISSUE TITLE
Unable to manually sort rows with Observable-wrapped store

### ISSUE THREAD

**Issue by sjlongland** [SitePen/dgrid#160]
Not sure if this is a core Dojo bug, or a bug in dgrid, or I'm DoingItWrong...

dgrid is great, but I notice two things with dgrid.  Firstly, it is not possible to cancel sorting by a particular column.  A lot of applications, the column header is tri-state; it's either sort ascending, descending or not at all, and clicking toggles between the three.  dgrid only toggles between the first two.

I'm not sure if this interferes with manual sorting or not.  I'd think that upon attempting to manually sort, any column sorting should be cancelled.  Which brings me to the actual problem, manual sorting doesn't appear to work.

http://www.longlandclan.yi.org/~stuartl/dojo-rtstore/dgrid.html is my test case.  I actually managed to get a real-time grid going, after being pointed to dgrid from the mailing list some time back.  If I try to drag a row, I notice it lets me drop it, but when I do, it stays put exactly where it was, it doesn't move where I dropped it.

Is this a bug in dgrid, (the undocumented) dojo.Stores.Observable, or something I'm doing wrong?
Regards,
Stuart Longland

**Comment by kfranqueiro** [comment]
Apologies for the insanely late reply on this, but I wanted to leave answers for the benefit of anyone else who happens to come across the same questions, too.

dgrid added support for a cancelable `dgrid-sort` event since v0.3.5 (released in January 2013).  It is possible to take advantage of this event to do what you want (this code will work with 0.3.5 or higher, including 0.4):

```js
    grid.on('dgrid-sort', function (event) {
        var grid = event.grid;
		var previousSort = grid.get('sort')[0];
		if (previousSort && previousSort.descending && event.sort[0].attribute === previousSort.attribute) {
			// Instead of toggling from descending straight to ascending, toggle back to neutral first
			event.preventDefault();
			grid._sortNode = null;
			grid.set('sort', []);
		}
    });
```

I'm also working on adding a `hasNeutralSort` option to Grid so you won't have to do the above in future major releases.

Regarding ordered stores and DnD, there are test pages and the todo demo pointed out previously on this thread which demonstrate doing this, but with dojo/store it required extending a store to support custom reordering, and re-sorting the data would generally destroy this ordering.  On the other hand, dstore (used by dgrid 0.4) has built-in support for a `beforeId` option, which `dgrid/extensions/DnD` takes advantage of to Just Work out of the box, at least for stores that incorporate client-side querying functionality (such as `dstore/Memory`, via `dstore/SimpleQuery`).
