### ISSUE TITLE
DropDownButton as editor in a cell

### ISSUE THREAD

**Issue by oyaaraas** [SitePen/dgrid#166]
There is a bug in the onClick event when having a DropDownButton, like this: http://jsfiddle.net/8cSxz/3/ as an editor in a cell.
The onClick event only fires if you click on the outermost span of the widget. Clicking in the middle will not fire the onClick event for some reason.

**Comment by kfranqueiro** [comment]
There are two separate problems here; one is referenced by #159 but that is not the problem the OP had (as that ticket involves Keyboard and does not involve Editor).

The other is that DropDownButton doesn't really make sense for use with `dgrid/Editor` because `dgrid/Editor` is intended for use with widgets with an explicit value for the purpose of updating data.  For this reason I'm closing this as invalid.
