### ISSUE TITLE
Select a row by index

### ISSUE THREAD

**Issue by Leftium** [SitePen/dgrid#169]
According to the [documentation](https://github.com/SitePen/dgrid/wiki/Migration-API), dgrid does not support `getItem(rowIndex)`  from the DataGrid API.

Is there some other way to get the id for the nth row? My usage scenario is to automatically select the first item from an ondemand dgrid using the selector column plugin.

**Comment by jmk201** [comment]
Hey Ken,
I am using dgrid for the first time and a little lost here.

I am able to populate a dgrid with some queried data and also made some columns editable. One of the columns has unique Id too. 

On a submit button, I save the edit using grid.save(). 

Now, I want to get each row of edited data . WHich is the best way to do it? 

SInce I have the unique id value of each row, how can I access the saved dirty data using the id? or is it better to get values from the domNode itself. If so how do I access the first row?  
I tried     grid.select(query(".dgrid-row", grid.domNode)[0]);  as per your above suggestion but it gives an error on 'query'. 

please help!!
thanks!!

**Comment by kfranqueiro** [comment]
Your question seems unrelated to the question here, which specifically has to do with the Selection mixin, not Editor and store operations.  I'd suggest asking your question on dojo-interest, SO, or IRC, as [suggested in the readme](https://github.com/SitePen/dgrid#getting-support).

**Comment by jmk201** [comment]
yes, clearly I am a little lost here. Should I create a new issue under a certain category? Let me try it.
