### ISSUE TITLE
Pagination extension doesn't work with real-time updates

### ISSUE THREAD

**Issue by larip** [SitePen/dgrid#302]
Using an observable data store and notify seems to break pagination extension.

Here's an example: http://jsfiddle.net/E2jWH/ (try switching between the pages)

**Comment by kfranqueiro** [comment]
This should be resolved in later 0.3.x releases as well as 0.4.  The Pagination extension will re-request the page if it needs to in order to ensure the appropriate number of rows are displayed.

I tried updating your fiddle to use dgrid 0.3.17 and it seems like it's working: http://jsfiddle.net/E2jWH/58/
