### ISSUE TITLE
best practice to scroll to selected row

### ISSUE THREAD

**Issue by derekwmiller** [SitePen/dgrid#342]
Anyone have any ideas on the best way to scroll to a selected row? I'm selecting the row based on row.ID (string, in this case) and verifying that the row is selected with the grid.isSelected(row) method... row is defined as row = grid.row(id) -- later grid.select(row).... however, I'm receiving an error that row has no method scrollTo(); or scrollIntoView();

Any input is appreciated.

thanks.

**Comment by AndrewHenryOttawa** [comment]
This worked for me...

var row = grid.row(rowId);
if (row){
      put(row.element, ".dgrid-selected");    // put-selector
      row.element.scrollIntoView();
}

Haven't tested it yet on a grid with a large amount of data, that is to say a grid that may have rows that aren't yet rendered because they are so far out of view.

**Comment by AndrewHenryOttawa** [comment]
My last comment doesn't work if the row hasn't been rendered yet.

row.element will be null in that case.

**Comment by kfranqueiro** [comment]
In case anyone else attempts to use the last example here as a reference, it is important to point out that it makes several assumptions:

* Your store is a synchronous store e.g. `dojo/store/Memory` (since the code assumes `query` returns an array)
* Your target browsers all support ES5 (since the code assumes that `lastIndexOf` exists on arrays)

It is also important to realize that performing an unbounded query (i.e. no start/count) somewhat defeats the purpose of the performance gains of querying specific ranges, as done by OnDemandList and Pagination.  It should go without saying, but this approach would be ill-advised with a server-based store.

If you're using a small in-memory store, you could get away with using something like the [SingleQuery mixin](http://dgrid.io/tutorials/0.3/single_query/) and then `row.element` would always be available since lazy rendering would be out of the picture.

**Comment by AndrewHenryOttawa** [comment]
Hi Ken,

Thanks for the feed back, it's always appreciated.

Your right about the first point. we are using dojo/store/memory 

Regarding your second point, is there a more resilient way of determining the index in this situation?

Also, my colleague pointed out that we could have just rendered all the rows with the SingleQuery mixin, but the grid has ~40 columns (client's requirements) with potentially ~500 rows. And there could be a number of instances of this grid. I kind of thought, from past experience with HTML tables (not dgrid) that we'd run into a performance issue. Is that a valid concern or am I being overly cautious?

**Comment by kfranqueiro** [comment]
> Regarding your second point, is there a more resilient way of determining the index in this situation?

`dojo/_base/array` has a cross-browser [`lastIndexOf` function](http://dojotoolkit.org/reference-guide/1.10/dojo/_base/array.html#lastindexof).

> Also, my colleague pointed out that we could have just rendered all the rows with the SingleQuery mixin, but the grid has ~40 columns (client's requirements) with potentially ~500 rows. And there could be a number of instances of this grid. I kind of thought, from past experience with HTML tables (not dgrid) that we'd run into a performance issue. Is that a valid concern or am I being overly cautious?

No, you're probably right in that case.  By using OnDemandList you're still benefiting from lazy rendering, even if you're still doing additional processing over the full data.  (Also that's a lot of columns in general...)

**Comment by AndrewHenryOttawa** [comment]
>Also that's a lot of columns in general...

Yup, internally we wonder at the usefulness of all those columns. But ours is not to question the client's desires!  :  )

Thanks again.
