### ISSUE TITLE
Enhancement request for ColumnResizer: double click column divider to auto size column width

### ISSUE THREAD

**Issue by lixopmstp** [SitePen/dgrid#528]
If you have used MS Excel you know what I mean.

**Comment by cafed00d4j** [comment]
@SitePenKenFranqueiro @kfranqueiro   It's been three years since this was closed. Is there a way we can achieve this now?

I've noticed that both google sheets and excel online have this feature working (sheets is considerable faster than excel online here)... however both the web versions still can't trump native excel...

I need to implement this feature for my job.. I'd be grateful for any advice/wisdom you could share before I go down the rabbit hole. :)
