### ISSUE TITLE
Improve documentation of the set('query', ...) method.

### ISSUE THREAD

**Issue by Cito** [SitePen/dgrid#698]
The page https://github.com/SitePen/dgrid/wiki/OnDemandList-and-OnDemandGrid should mention in the documentation of the set('query', ...) method that it is possible to pass the sort property via the queryOptions. This is better than calling set('query', ...) and then set('sort', ...) because that would request the store and refresh the grid two times.

**Comment by kfranqueiro** [comment]
You raise a good point - the query-setting logic is accounting for `sort` if it is passed in `queryOptions` to keep dgrid's internal state consistent, as well.

However, this is somewhat obsoleted in dgrid 0.4, since both `set('query')` and `set('store')` are replaced by `set('collection')`.  Even if the collection it is passed has a pre-existing sort, dgrid won't know about it, and will apply its own sort on top of the passed collection.

I apologize for not getting back to this issue sooner; I will make a note to update this documentation in the event another 0.3 release ends up planned, but none is planned at the moment.
