### ISSUE TITLE
No listener installed for empty Observable MemoryStore; dgrid not updating

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [SitePen/dgrid#788]
Hi,

there seems to be a regression in the current dgrid master and also at least version 0.3.12 that relates to the handling of Observable Memory stores since dgrid 0.3.8. I'm sorry that I have no Fiddler to reproduce the problem but I've already spent several hours on the issue because I thought it related to my code ...

On a form I've got a "new" button that adds entities to a Observable Memory store. If the store is already populated with at least one element (loaded before the store property of the dgrid instance is set) pressing new automatically updates the dgrid; If the store is empty on form startup the instances will be added to the store and other UI elements updated - but NOT the dgrid; while debugging I found out there was no listener added. If I go back to dgrid 0.3.8 my code is again working as expected.

Best regards,
Harald Mühlhoff

www.carecom.de

PS: BTW - thx for dgrid; beside this issue it has been a pleasure to use so far!

```
var store = new Observable(new Memory({ idProperty: 'nr' }));

// [...] If there load entities into store

var CustomGrid = declare([OnDemandGrid, DijitRegistry, Keyboard, Selection]);

var dgrid = new CustomGrid({
                    columns: this.computeColumns(),
                    deselectOnRefresh: false,
                    store: store,
                    query: {},
                    selectionMode: "single", // for Selection; only select a single row at a time
                    cellNavigation: false // for Keyboard; allow only row-level keyboard navigation

                }, this._grid);
```

**Comment by adros** [comment]
I have also come across this problem. It's caused by wrapping Observable store in a `dojo/store/Cache`. The logic of `_StoreMixin` you have mentioned does not work in this case, because it aspects the `notify` method on delegated object, the original method stays untouched and your aspect is never called.

I could solve my issue by changing the order of wrapping (wrap Cache to Observable), but I still do not very like the _StoreMixin's solution - to refresh the store.

I prefer setting `cleanEmptyObservers:false`, but is it safe? What is the purpose of this property? What else does it handle and what can go wronge after changing the default value? (e.g. inserting items in result sets that are out of view, etc.. ?)
