### ISSUE TITLE
"Lazy-loading tree grid" test is invalid (and issue).

### ISSUE THREAD

**Issue by GordonSmith** [SitePen/dgrid#874]
1.  The code does not actually do a lazy load.  To fix add "true" to the DeferredWrapper @ line 239:
   
   ```
   testCountryStores= new Observable(new DeferredWrapper(testSyncCountryStore, true));
   ```
2.  Having made the change expand the bottom items:
   ![image](https://f.cloud.github.com/assets/966863/2493089/0ef20b5a-b27a-11e3-9c8f-903dcb6295b7.png)
   Then click on "Show All", you then end up with:
   ![image](https://f.cloud.github.com/assets/966863/2493091/3d4ac28a-b27a-11e3-90c6-21e0dce66d36.png)
   Oddly to "fix" the view, you just need to move the "mouse over" the bottom few rows...

**Comment by matsamuel** [comment]
It is documented that this issue has been fixed in dgrid 3.16 however we are using 3.16 and still seeing the same issue. As a temporary measure we are setting "enableTransitions" to "false" for the moment (as that alleviates the problem). Is it possible that this issue was re-introduced some how before 3.16 went out? It's also possible that I'm just seeing a different occurrence of the same problem. Either way can this issue please be re-opened?
